<a href="https://colab.research.google.com/github/Sittii/SHRISTI_OJT/blob/main/OJT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sp
import scipy.linalg

In [ ]:
#QUESTION 2:Row Echelon Form:
# Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations.

In [ ]:

# create random matrix
np.random.seed(23)
A= np.random.randint(0,10,(5,5))
A

array([[3, 6, 8, 9, 6],
       [8, 7, 9, 3, 6],
       [1, 2, 5, 5, 0],
       [5, 0, 9, 9, 3],
       [1, 7, 4, 1, 1]])

In [ ]:
#ROW ECHLON FORM THROUGH ROW TRANSFORMATIONS
A[0]=A[0]/3
A[0]

array([1, 2, 2, 3, 2])

In [ ]:
A[1]=A[1]-8*A[0]
A[1]

array([  0,  -9,  -7, -21, -10])

In [ ]:
A[2]=A[2]-A[0]
A[2]

array([ 0,  0,  3,  2, -2])

In [ ]:
A[3]=A[3]-5*A[0]
A[3]

array([  0, -10,  -1,  -6,  -7])

In [ ]:
A[4]=A[4]-A[0]
A[4]

array([ 0,  5,  2, -2, -1])

In [ ]:
A[1]=A[1]/-9
A[1]

array([0, 1, 0, 2, 1])

In [ ]:
A

array([[  1,   2,   2,   3,   2],
       [  0,   1,   0,   2,   1],
       [  0,   0,   3,   2,  -2],
       [  0, -10,  -1,  -6,  -7],
       [  0,   5,   2,  -2,  -1]])

In [ ]:
A[3]=A[3]+10*A[1]
A[3]

array([ 0,  0, -1, 14,  3])

In [ ]:
A[4]=A[4]-5*A[1]
A[4]

array([  0,   0,   2, -12,  -6])

In [ ]:
A

array([[  1,   2,   2,   3,   2],
       [  0,   1,   0,   2,   1],
       [  0,   0,   3,   2,  -2],
       [  0,   0,  -1,  14,   3],
       [  0,   0,   2, -12,  -6]])

In [ ]:
A[2]=A[2]/3
A[2]

array([0, 0, 1, 0, 0])

In [ ]:
A[3]=A[3]+A[2]
A[3]

array([ 0,  0,  0, 14,  3])

In [ ]:
A[4]=A[4]-2*A[2]
A[4]

array([  0,   0,   0, -12,  -6])

In [ ]:
A

array([[  1,   2,   2,   3,   2],
       [  0,   1,   0,   2,   1],
       [  0,   0,   1,   0,   0],
       [  0,   0,   0,  14,   3],
       [  0,   0,   0, -12,  -6]])

In [ ]:
A[3]=A[3]/14
A[3]

array([0, 0, 0, 1, 0])

In [ ]:
A[4]=A[4]+12*A[3]
A[4]

array([ 0,  0,  0,  0, -6])

In [ ]:
A

array([[ 1,  2,  2,  3,  2],
       [ 0,  1,  0,  2,  1],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, -6]])

In [ ]:
A[4]=A[4]/-6
A

array([[1, 2, 2, 3, 2],
       [0, 1, 0, 2, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])